-- Seed: Dhriti/Pavani Hall weekly menu (16-31 Aug 2026 PDF; repeats weekly).
insert into messes (name, hostels) values ('Dhriti', '{"Dhriti/Pavani Hall"}') on conflict (name) do nothing;
insert into menu_items (mess_id, day_of_week, meal, name, position)
select (select id from messes where name = 'Dhriti'), v.d, v.m, v.n, v.p from (values
(1,'Breakfast','Maccroni/Sweet Corn',0),
(1,'Breakfast','Paneer Parantha',1),
(1,'Breakfast','Hot/Cold Milk',2),
(1,'Breakfast','Tea',3),
(1,'Breakfast','Brown Bread',4),
(1,'Breakfast','Mix Jam',5),
(1,'Breakfast','Butter',6),
(1,'Breakfast','Green Chutney',7),
(1,'Breakfast','Cut Fruit',8),
(1,'Breakfast','Boiled Egg & Omelette',9),
(2,'Breakfast','Cornflakes',0),
(2,'Breakfast','Mix Veg Parantha',1),
(2,'Breakfast','Hot/Cold Milk',2),
(2,'Breakfast','Tea',3),
(2,'Breakfast','Brown Bread',4),
(2,'Breakfast','Mix Jam',5),
(2,'Breakfast','Butter',6),
(2,'Breakfast','Strawberry Yogurt',7),
(2,'Breakfast','Whole Fruit',8),
(2,'Breakfast','Boiled Egg & Bhurji',9),
(3,'Breakfast','Veg Cutlet/Bread Pakoda',0),
(3,'Breakfast','Dal Paratha',1),
(3,'Breakfast','Hot/Cold Milk',2),
(3,'Breakfast','Tea',3),
(3,'Breakfast','Brown Bread',4),
(3,'Breakfast','Mix Jam',5),
(3,'Breakfast','Butter',6),
(3,'Breakfast','Curd',7),
(3,'Breakfast','Cut Fruit',8),
(3,'Breakfast','Boiled Egg & Omelette',9),
(4,'Breakfast','Bombay Sandwich',0),
(4,'Breakfast','Besan Chilla',1),
(4,'Breakfast','Hot/Cold Milk',2),
(4,'Breakfast','Tea',3),
(4,'Breakfast','Brown Bread',4),
(4,'Breakfast','Mix Jam',5),
(4,'Breakfast','Butter',6),
(4,'Breakfast','Green Chutney',7),
(4,'Breakfast','Whole Fruit',8),
(4,'Breakfast','Boiled Egg & Bhurji',9),
(5,'Breakfast','Peanut Poha',0),
(5,'Breakfast','Aloo Pyaz Paratha',1),
(5,'Breakfast','Hot/Cold Milk',2),
(5,'Breakfast','Tea',3),
(5,'Breakfast','Brown Bread',4),
(5,'Breakfast','Mix Jam',5),
(5,'Breakfast','Butter',6),
(5,'Breakfast','Curd',7),
(5,'Breakfast','Cut Fruit',8),
(5,'Breakfast','Boiled Egg & Bhurji',9),
(6,'Breakfast','Sweet Daliya',0),
(6,'Breakfast','Plain Paratha/Black Channa Masala',1),
(6,'Breakfast','Hot/Cold Milk',2),
(6,'Breakfast','Tea',3),
(6,'Breakfast','Brown Bread',4),
(6,'Breakfast','Mix Jam',5),
(6,'Breakfast','Butter',6),
(6,'Breakfast','Curd',7),
(6,'Breakfast','Boiled Egg & Bhurji',8),
(7,'Breakfast','Cornflakes',0),
(7,'Breakfast','Aloo Parantha',1),
(7,'Breakfast','Hot/Cold Milk',2),
(7,'Breakfast','Tea',3),
(7,'Breakfast','Brown Bread',4),
(7,'Breakfast','Mix Jam',5),
(7,'Breakfast','Butter',6),
(7,'Breakfast','Curd',7),
(7,'Breakfast','Boiled Egg & Omelette',8),
(1,'Lunch','Rajmah Raseela',0),
(1,'Lunch','Khatta Meetha Petha',1),
(1,'Lunch','Jeera Rice',2),
(1,'Lunch','Chapati',3),
(1,'Lunch','OTC Raita',4),
(1,'Lunch','Lemon Water',5),
(1,'Lunch','Mix Salad (with beetroot)',6),
(2,'Lunch','Sambhar',0),
(2,'Lunch','Uttapam',1),
(2,'Lunch','Lemon Rice',2),
(2,'Lunch','Vada',3),
(2,'Lunch','Coconut Chutney',4),
(2,'Lunch','Aam Panna',5),
(2,'Lunch','Fryums',6),
(3,'Lunch','Black Channa',0),
(3,'Lunch','Nutri Keema Muttar',1),
(3,'Lunch','Plain Rice',2),
(3,'Lunch','Chapati',3),
(3,'Lunch','Mint & Coriander Raita',4),
(3,'Lunch','Orange Tang',5),
(3,'Lunch','Green Salad',6),
(4,'Lunch','Kadhi Pakoda',0),
(4,'Lunch','Aloo Jeera',1),
(4,'Lunch','Plain Rice',2),
(4,'Lunch','Chapati',3),
(4,'Lunch','Ice Tea',4),
(4,'Lunch','Green Salad',5),
(5,'Lunch','Kulcha/Pav',0),
(5,'Lunch','Bhaji/Cholle',1),
(5,'Lunch','Veg Biryani/Plain Rice',2),
(5,'Lunch','Mint Chutney',3),
(5,'Lunch','Boondi Raita',4),
(5,'Lunch','Jaljeera',5),
(5,'Lunch','Laccha Onion',6),
(6,'Lunch','Matar Paneer (home style)',0),
(6,'Lunch','Channa Dal',1),
(6,'Lunch','Jeera Rice',2),
(6,'Lunch','Chapati',3),
(6,'Lunch','Cucumber Raita',4),
(6,'Lunch','Roohafza',5),
(6,'Lunch','Green Salad',6),
(7,'Lunch','Masala Poori/Bhature',0),
(7,'Lunch','Aloo Bhaji/Cholle',1),
(7,'Lunch','Steamed Rice',2),
(7,'Lunch','Mint Chutney',3),
(7,'Lunch','Sweet Lassi',4),
(7,'Lunch','Laccha Onion',5),
(1,'Dinner','Aloo Mattar',0),
(1,'Dinner','Black Masoor Dal',1),
(1,'Dinner','Plain Rice',2),
(1,'Dinner','Chapati',3),
(1,'Dinner','Green Salad',4),
(1,'Dinner','Curd',5),
(1,'Dinner','Sooji Halwa',6),
(1,'Dinner','Chat Papdi (once in 15 days)',7),
(2,'Dinner','Bhindi Do Pyaza',0),
(2,'Dinner','Dal Panchratan',1),
(2,'Dinner','Jeera Rice',2),
(2,'Dinner','Chapati',3),
(2,'Dinner','Sprouts Salad',4),
(2,'Dinner','Curd',5),
(2,'Dinner','Besan Barfi',6),
(3,'Dinner','Kadhai Paneer/Paneer Do Pyaza',0),
(3,'Dinner','Moong Masoor Dal',1),
(3,'Dinner','Jeera Rice',2),
(3,'Dinner','Tandoori Roti',3),
(3,'Dinner','Sirka Onion',4),
(3,'Dinner','Curd',5),
(3,'Dinner','Ice Cream',6),
(3,'Dinner','Egg Curry (once in 15 days)',7),
(4,'Dinner','White/Red Sauce Pasta',0),
(4,'Dinner','Dal Dhaba',1),
(4,'Dinner','Plain Rice',2),
(4,'Dinner','Chapati',3),
(4,'Dinner','Green Salad',4),
(4,'Dinner','Curd',5),
(4,'Dinner','Fruit Cake/Brownie',6),
(5,'Dinner','Sabjiyon Ka Mela',0),
(5,'Dinner','Dal Makhani',1),
(5,'Dinner','Soya Rice',2),
(5,'Dinner','Chapati',3),
(5,'Dinner','Corn Salad/Maccroni Salad',4),
(5,'Dinner','Curd',5),
(5,'Dinner','Jalebi',6),
(6,'Dinner','Arbi Masala',0),
(6,'Dinner','Dal Fry',1),
(6,'Dinner','Chickpea Pulao',2),
(6,'Dinner','Chapati',3),
(6,'Dinner','3 Bean Salad',4),
(6,'Dinner','Curd',5),
(6,'Dinner','Gulab Jamun',6),
(7,'Dinner','Chilli Soya',0),
(7,'Dinner','Punjabi Dal',1),
(7,'Dinner','Plain Rice',2),
(7,'Dinner','Chapati',3),
(7,'Dinner','Green Salad',4),
(7,'Dinner','Curd',5),
(7,'Dinner','Coconut Laddoo',6)
) as v(d, m, n, p) on conflict do nothing;
